name: Build and Verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-upload:
    name: Build for ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write

    steps:

    - name: Check out Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder jq
        pipx install flatpak-node-generator

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - name: Generate Flatpak sources
      run: |
        rm -f flatpak/generated-sources.json
        flatpak-node-generator --no-requests-cache npm package-lock.json --output flatpak/generated-sources.json

    - name: Install npm dependencies and verify build
      run: |
        npm ci
        npm run build-base

    - name: Build Flatpak repo
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user remote-modify --enable flathub
        git config --global --add safe.directory ${{ github.workspace }}
        flatpak-builder --arch=${{ matrix.arch }} --jobs=1 --user --disable-rofiles-fuse --install-deps-from=flathub --force-clean --repo=repo _build flatpak/dev.mukkematti.qobuz-linux.yml
